In [3]:
!pip install scikit-learn

In [7]:
import sklearn
import pandas as pd
import numpy as np

In [5]:
%pip install mglearn
import mglearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

Note: you may need to restart the kernel to use updated packages.


In [6]:
X,y=mglearn.datasets.make_wave(n_samples=60)
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42)

In [8]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [9]:
model.predict(X_test)

array([-0.3283204 , -0.84483835, -0.49358667,  0.35230624, -0.71167167,
        0.19957573,  1.02910669,  0.07859229,  0.75390167, -0.75032857,
       -0.47681266,  1.07802761, -0.8104986 ,  0.2013684 ,  1.00692209])

In [11]:
model.score(X_test,y_test)

0.65933685968637

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import mglearn

X,y= mglearn.datasets.load_extended_boston()
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)
regression=LinearRegression().fit(X_train,y_train)

print("Training set score:{:.2f}".format(regression.score(X_train,y_train)))
print("Test set score:{:.2f}".format(regression.score(X_test,y_test)))

pred=regression.predict(X_test)
print("Predictions:\n",pred)
print("Estimations",y_test)

Training set score:0.95
Test set score:0.61
Predictions:
 [ 23.65294082  26.73756431  29.61078314  10.15490293  19.63821608
  19.69567722  22.04569772  20.8219241   11.62647856  17.55251923
   6.02831471  13.30819476  14.08746399   8.24933315  48.92086715
  35.54459237  23.67706411  37.23811936  32.28994966  22.44461026
  25.04445792  21.34495855  20.89993569  27.34950626  18.20884762
  30.05914961  16.38882367  18.27410131  34.58728224  13.84776749
  16.56901813  18.20821168  20.00399253  19.68630353  26.44755882
  16.35902867   7.10012009  36.71844063  16.76163017  13.4975915
  22.14796642  19.86834244  19.74483033  19.04895022  11.823238
  22.30991276  17.95961579   9.9207432   12.34654968  23.09629767
 -26.05316354  25.18108608  20.72351713  52.44146808   5.7506184
  21.16062991  16.67681922  17.94789708  17.07672773  19.79482458
  23.94848059  21.07920154  33.14839064  29.17411146  19.31538063
  30.77385559  15.19001363  19.27968125  14.28902591  21.0217457
  18.17979319  21.77419

In [26]:
import mglearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X,y=mglearn.datasets.make_wave(n_samples=60)
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42)
lr=LinearRegression().fit(X_train,y_train)
print("lr.coef_:{}".format(lr.coef_))
print("lr.intercept_:{}".format(lr.intercept_))
print("Training set score:{:.2f}".format(lr.score(X_train,y_train)))

lr.coef_:[0.39390555]
lr.intercept_:-0.031804343026759746
Training set score:0.67


In [27]:
import mglearn
from sklearn.model_selection import train_test_split
X,y=mglearn.datasets.load_extended_boston()
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42)

In [28]:
from sklearn.linear_model import Ridge
ridge=Ridge().fit(X_train,y_train)
print("Training set score:",format(ridge.score(X_train,y_train)))
print("Test set score:",format(ridge.score(X_test,y_test)))

Training set score: 0.8700969775259918
Test set score: 0.8145421818415555


In [29]:
from sklearn.linear_model import Ridge

alphas = [0.001, 0.01, 0.1, 1, 10, 100]
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train, y_train)
    print(f"Alpha: {a:.3f}")
    print(f"Training score: {ridge.score(X_train, y_train):.3f}")
    print(f"Test score: {ridge.score(X_test, y_test):.3f}")
    print("-" * 30)


Alpha: 0.001
Training score: 0.943
Test score: 0.806
------------------------------
Alpha: 0.010
Training score: 0.936
Test score: 0.814
------------------------------
Alpha: 0.100
Training score: 0.917
Test score: 0.825
------------------------------
Alpha: 1.000
Training score: 0.870
Test score: 0.815
------------------------------
Alpha: 10.000
Training score: 0.767
Test score: 0.728
------------------------------
Alpha: 100.000
Training score: 0.562
Test score: 0.547
------------------------------


In [30]:
import mglearn
from sklearn.model_selection import train_test_split
X,y=mglearn.datasets.load_extended_boston()
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42)

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso

lasso=Lasso().fit(X_train,y_train)
print("Training set score:",format(lasso.score(X_train,y_train)))
print("Test set score:",format(lasso.score(X_test,y_test)))

Training set score: 0.26783778369518485
Test set score: 0.2599232118344591


In [32]:
alphas=[0.01,0.1,1,0.2,0.3,0.4,10,100]
for i in alphas:
      lasso2=Lasso(alpha=i ,max_iter=10000).fit(X_train,y_train)
      print("Training set score for alpha {}: {:.2f}".format(i,lasso2.score(X_train,y_train)))
      print("Test set score for alpha {}: {:.2f}".format(i,lasso2.score(X_test,y_test)))
      print("*"*30)

Training set score for alpha 0.01: 0.89
Test set score for alpha 0.01: 0.80
******************************
Training set score for alpha 0.1: 0.75
Test set score for alpha 0.1: 0.70
******************************
Training set score for alpha 1: 0.27
Test set score for alpha 1: 0.26
******************************
Training set score for alpha 0.2: 0.72
Test set score for alpha 0.2: 0.67
******************************
Training set score for alpha 0.3: 0.69
Test set score for alpha 0.3: 0.65
******************************
Training set score for alpha 0.4: 0.65
Test set score for alpha 0.4: 0.62
******************************
Training set score for alpha 10: 0.00
Test set score for alpha 10: -0.03
******************************
Training set score for alpha 100: 0.00
Test set score for alpha 100: -0.03
******************************


In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split


%pip install load_breast_cancer
from sklearn.datasets import load_breast_cancer
cancer=load_breast_cancer()
X_train,X_test,y_train,y_test=train_test_split(cancer.data,cancer.target,random_state=66)
training_accuracy=[]
test_accuracy=[]
neighbors_settings=range(1,11)
for n_neighbors in neighbors_settings:
    clf=KNeighborsClassifier(n_neighbors=n_neighbors)
    clf.fit(X_train,y_train)
    training_accuracy.append(clf.score(X_train,y_train))
    test_accuracy.append(clf.score(X_test,y_test))

ERROR: Could not find a version that satisfies the requirement load_breast_cancer (from versions: none)
ERROR: No matching distribution found for load_breast_cancer


Note: you may need to restart the kernel to use updated packages.


In [36]:
from sklearn.datasets import load_iris
Iris_dataset = load_iris()
Iris_dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [37]:
print("Keys of Iris_dataset\n{}".format(Iris_dataset.keys()))

Keys of Iris_dataset
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [38]:
print("First five columns of data: \n{}".format(Iris_dataset['data'][:5]))

First five columns of data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [39]:
import pandas as pd
import numpy as np

Iris_df=pd.DataFrame(data=np.c_[Iris_dataset['data'], Iris_dataset['target']], columns=Iris_dataset['feature_names']+['target'])
Iris_df


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

In [40]:
Iris_df.isnull().sum()


sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Iris_dataset['data'], Iris_dataset['target'], random_state=0, test_size=0.3)

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=17)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=17)

In [42]:
predictions = model.predict(X_test)
predictions

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [43]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0])

In [44]:
accuracy=model.score(X_test, y_test)
accuracy

0.9777777777777777

In [45]:
x_new=np.array([[4.5,2.3,6.9,2.5]])
prediction=model.predict(x_new)
prediction
print("prediction target name is {}".format(Iris_dataset['target_names'][prediction]))

prediction target name is ['virginica']


In [46]:
X,y=mglearn.datasets.make_wave(n_samples=40)
df=pd.DataFrame(np.c_[X,y],columns=["Features","Class"])
display(df)

Features     Class
0  -0.752759 -0.448221
1   2.704286  0.331226
2   1.391964  0.779321
3   0.591951  0.034979
4  -2.063888 -1.387736
5  -2.064033 -2.471962
6  -2.651498 -1.527308
7   2.197057  1.494172
8   0.606690  1.000324
9   1.248435  0.229562
10 -2.876493 -1.059796
11  2.819459  0.778964
12  1.994656  0.754188
13 -1.725965 -1.513697
14 -1.909050 -1.673034
15 -1.899573 -0.904970
16 -1.174547  0.084485
17  0.148539 -0.527347
18 -0.408330 -0.541146
19 -1.252625 -0.340907
20  0.671117  0.217782
21 -2.163037 -1.124691
22 -1.247132  0.372991
23 -0.801829  0.097563
24 -0.263580 -0.986181
25  1.711056  0.966954
26 -1.801957 -1.134550
27  0.085407  0.697986
28  0.554487  0.436558
29 -2.721298 -0.956521
30  0.645269  0.035279
31 -1.976855 -2.085817
32 -2.609690 -0.474110
33  2.693313  1.537083
34  2.793792  0.868933
35  1.850384  1.876649
36 -1.172317  0.094526
37 -2.413967 -1.415024
38  1.105398  0.254389
39 -0.359085  0.093989

In [47]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)
reg=KNeighborsRegressor(n_neighbors=3)
reg.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=3)

In [48]:
y_pred=reg.predict(X_test)
print("Precitions",y_pred)

Precitions [-0.05396539  0.35686046  1.13671923 -1.89415682 -1.13881398 -1.63113382
  0.35686046  0.91241374 -0.44680446 -1.13881398]


In [49]:
reg.score(X_test,y_test)

0.8344172446249605

In [50]:
import mglearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [51]:
linear=LinearRegression().fit(X_train,y_train)
print("Linear.coef W: {}".format(linear.coef_))
print("Linear.intercept B: {}".format(linear.intercept_))

Linear.coef W: [0.39390555]
Linear.intercept B: -0.031804343026759746
